name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

  publish-npm:
    name: Publishing to npm
    environment: production
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: fregante/setup-git-user@v1
      - run: git config user.name "GitHub Actions Publish"
      - run: git config user.email "actions@users.noreply.github.com"
      - run: npm version patch
      - run: git add .;
      - run: git commit -m "Update Version"
      - run: git push
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
